create table if not exists projects (
    id bigint generated by default as identity primary key,
    name text not null,
    description text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

alter table documents add column if not exists project_id bigint references projects(id) on delete set null;
alter table documents add column if not exists document_name text;
alter table documents add column if not exists template_name text;
alter table documents add column if not exists file_path text;
alter table documents add column if not exists is_favorite boolean not null default false;
alter table documents add column if not exists updated_at timestamptz not null default now();

create index if not exists documents_project_id_idx on documents(project_id);
create index if not exists documents_favorite_idx on documents(is_favorite) where is_favorite = true;